-- LIVE DDL dump — generated by helpers/misc/schema_dump.py; DO NOT EDIT
-- source: memory/convo_search_fts.db (sqlite)
-- body sha256: cdc556f8cfc6
-- refresh: make schema-dump
CREATE VIRTUAL TABLE convo_fts USING fts5(text, harness UNINDEXED, part_id UNINDEXED, session_id UNINDEXED, tokenize='porter unicode61');
