-- LIVE DDL dump — generated by helpers/misc/schema_dump.py; DO NOT EDIT
-- source: memory/corpus.db (sqlite)
-- body sha256: 2217473c243e
-- refresh: make schema-dump
CREATE TABLE corpus_cache(path TEXT PRIMARY KEY, mtime REAL, content_hash TEXT, frontmatter_json TEXT, body TEXT);
