-- LIVE DDL dump — generated by helpers/misc/schema_dump.py; DO NOT EDIT
-- source: memory/doc_search.db (sqlite)
-- body sha256: a2d4cb68fa78
-- refresh: make schema-dump
CREATE VIRTUAL TABLE doc_search USING fts5(title, section_title, file_path UNINDEXED, anchor UNINDEXED, content, embedding UNINDEXED, tokenize = 'porter unicode61');
