-- LIVE DDL dump — generated by helpers/misc/schema_dump.py; DO NOT EDIT
-- source: memory/embed_store.db (sqlite)
-- body sha256: 940ecfdd1930
-- refresh: make schema-dump
CREATE TABLE embed_cache ( text_hash TEXT NOT NULL, model     TEXT NOT NULL, embedding TEXT NOT NULL, source    TEXT NOT NULL DEFAULT '', PRIMARY KEY (text_hash, model));
CREATE VIRTUAL TABLE note_search_vec USING vec0(file_path TEXT PRIMARY KEY, embedding FLOAT[512] distance_metric=cosine);
