-- LIVE DDL dump — generated by helpers/misc/schema_dump.py; DO NOT EDIT
-- source: memory/md_lint_cache.db (sqlite)
-- body sha256: 3bb741898a50
-- refresh: make schema-dump
CREATE TABLE meta (key TEXT PRIMARY KEY, value TEXT);
CREATE TABLE verdicts (path TEXT PRIMARY KEY, hash TEXT NOT NULL, violations TEXT NOT NULL);
