-- LIVE DDL dump — generated by helpers/misc/schema_dump.py; DO NOT EDIT
-- source: memory/memory_search.db (sqlite)
-- body sha256: b6922f79beba
-- refresh: make schema-dump
CREATE VIRTUAL TABLE memory_search USING fts5(title, kind UNINDEXED, name UNINDEXED, source_path UNINDEXED, purpose UNINDEXED, content, embedding UNINDEXED, tokenize = 'porter unicode61');
