-- LIVE DDL dump — generated by helpers/misc/schema_dump.py; DO NOT EDIT
-- source: memory/script_search.db (sqlite)
-- body sha256: 88c1609f0704
-- refresh: make schema-dump
CREATE VIRTUAL TABLE script_search USING fts5(title, kind UNINDEXED, rel_path UNINDEXED, area UNINDEXED, purpose UNINDEXED, content, embedding UNINDEXED, tokenize = 'porter unicode61');
