#!/usr/bin/env python3
"""
Unified Notes Verification Script for FinData Knowledge Graph.

Validates every markdown note under findata/Companies, findata/Sectors,
and findata/Super_Sectors.

Checks are split by severity:

  ERROR   — structural invariants. Count toward the exit code / QA gate.
            (YAML parse, required fields, normalized_name <-> filename sync,
             filename format, type value, sector permalink, content quality.)

  WARNING — advisory style drift. Reported but never fail the gate.
            (tag taxonomy format, missing recommended fields.)

Run:  python3 helpers/validators/verify_notes.py
Exit: 0 if no ERRORs, else nonzero.
"""

import os
import re
import sys
from collections import Counter
from concurrent.futures import ProcessPoolExecutor
from datetime import datetime
from difflib import SequenceMatcher
from pathlib import Path

import yaml

# Make `helpers.*` importable when this script is invoked directly via the
# Makefile (`python3 helpers/validators/verify_notes.py`), not just under
# pytest (where conftest.py already inserts the repo root). Mirrors the shim in
# helpers/core/sync_tags.py.
_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from helpers.core.frontmatter import yaml_safe_load  # noqa: E402
from helpers.validators.static_checks import CANONICAL_SECTORS

# Lowercased canonical sector names for case-insensitive scalar matching.
_SECTOR_NAMES = set(CANONICAL_SECTORS)
_SECTOR_NAMES_LOWER = {s.lower() for s in CANONICAL_SECTORS}
_SECTOR_LOWER_TO_CANON = {s.lower(): s for s in CANONICAL_SECTORS}

# super_sector notes live under findata/Super_Sectors (9 GICS-style groups,
# generated by build_sector_hierarchy.py). sub_sector has no note files
# (facets are authored inside sector notes), but is listed for forward
# consistency so a stray sub_sector-typed note wouldn't be rejected as a
# bad type value — it would just find no directory to scan.
VALID_TYPES = {"company", "sector", "super_sector", "sub_sector", "theme"}

# OKF v0.2 provenance keys (doc/okf/README.md): optional on every schema-targeted
# note (doc/okf/frontmatter.*.v1.json). The strict sector/super_sector
# field allowlists below must mirror the schemas or the first OKF stamp on
# those trees fails the gate (company notes have no strict allowlist).
OKF_OPTIONAL_FIELDS = frozenset({"generated", "verified", "sources", "status", "stale_after"})

# Filename rules (see doc/design/findata.md §Sync Rules): PascalCase + single underscores,
# no special chars, no consecutive/trailing underscores, <= 100 chars.
# Allow leading digit for brand names that legitimately start with a number
# (e.g. "360_ONE_WAM"). Underscores and other constraints still apply downstream.
_FILENAME_OK = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_]*$")
# Standard tag taxonomy: lowercase category/value (value may be alphanumeric).
_TAG_OK = re.compile(r"^[a-z_]+/[a-z0-9_]+$")

# Known-good tag VALUES per controlled namespace (D3, 2026-07-30). Derived
# empirically from the WHOLE vault (company + sector + super-sector notes) so
# every value currently in the notes PASSES; the tag_value WARNING only fires on
# NEW sprawl. This is drift prevention, not a retroactive vocabulary collapse —
# the conservative D3 choice deliberately keeps all existing values valid
# (risk_investment/business_model are genuinely multi-dimensional and hard to
# collapse without judgment). Free-vocabulary namespaces (industry/
# industry_characteristics/specialization/ownership/product_category/
# financial_tags/confidence/holding_company/international_operations) are
# intentionally NOT listed here and left open.
_KNOWN_TAG_VALUES = {
    "entity_type": frozenset({"company", "sector", "super_sector", "sub_sector", "theme"}),
    "sector": frozenset(s.lower() for s in CANONICAL_SECTORS),
    "market_cap": frozenset({"large_cap", "mid_cap", "small_cap", "micro_cap", "null"}),
    "geography": frozenset(
        {
            "india",
            "global",
            "international",
            "domestic_focused",
            "usa",
            "pan_india",
            "north_india",
            "west_india",
            "south_asia",
            "south_korea",
        }
    ),
    "business_model": frozenset(
        {
            "b2b",
            "b2c",
            "b2b2c",
            "platform",
            "b2g",
            "saas",
            "mixed",
            "traditional_banking",
            "financial_services",
            "financial",
            "financial_infrastructure",
            "digital_platform",
            "cold_chain",
            "third_party_logistics",
            "integrated_logistics",
            "automotive_logistics",
            "supply_chain",
            "warehousing",
            "temperature_controlled",
            "pharmaceutical_logistics",
            "freight_services",
            "food_logistics",
            "transportation",
            "cost_optimization",
        }
    ),
    "risk_investment": frozenset(
        {
            "growth",
            "medium_risk",
            "high_growth",
            "dividend",
            "low_risk",
            "cyclical",
            "defensive",
            "high_risk",
            "stable",
            "regulatory_risk",
            "commodity",
            "stable_growth",
            "government",
            "consumer_cyclical",
            "sovereign",
            "regulatory",
            "financial_stability",
            "defense",
            "commodity_risk",
            "commodity_price_volatility",
            "weather_dependent",
            "speculative",
            "specialized_niche",
            "mixed",
            "microfinance",
            "infrastructure",
            "government_risk",
            "government_dependent",
            "gold_backed",
            "financial_risk",
            "contractual",
            "brand_risk",
            "automotive_cycle",
            # values used only in SECTOR notes (richer risk vocabulary there)
            "capex_intensive",
            "competition",
            "construction_cyclical",
            "content_risk",
            "cyclical_exposure",
            "economic_cycle",
            "environmental_regulatory",
            "interest_rate_sensitive",
            "operational_complexity",
            "raw_material_cost",
            "regulatory_heavy",
            "seasonal",
            "technology_disruption",
        }
    ),
    "investment_theme": frozenset(
        {
            "automation",
            "clean_energy",
            "energy_independence",
            "energy_infrastructure",
            "energy_security",
            "energy_transition",
            "government_owned",
            "government_schemes",
            "grid_modernization",
            "infrastructure",
            "infrastructure_development",
            "inland_waterways",
            "international_expansion",
            "make_in_india",
            "natural_gas",
            "power_infrastructure",
            "railway_capex",
            "renewable_energy",
            "resource_optimization",
            "sustainability",
            "sustainable_mining",
            "vehicle_finance",
            # values used only in SECTOR notes
            "commodity",
            "consumer_trend",
            "consumption_growth",
            "cyclical",
            "defensive",
            "digital_transformation",
            "dividend",
            "ev_transition",
            "financial_inclusion",
            "growth",
            "risk_management",
            "value",
        }
    ),
}


class NotesVerifier:
    def __init__(self, project_root=None):
        self.project_root = project_root or Path(__file__).parent.parent.parent
        # When True (worker processes), suppress progress prints to avoid
        # interleaved stdout across parallel workers.
        self.suppress_progress = False

        # ERROR buckets (gate-failing)
        self.issues = {
            "yaml_structure": [],
            "name_sync": [],
            "filename_format": [],
            "content_minimal": [],
            "content_missing_structure": [],
            "duplicates": [],
        }
        # WARNING buckets (advisory)
        self.warnings = {
            "tag_format": [],
            "tag_value": [],
            "missing_field": [],
            "field_order": [],
            "company_title_quoted": [],
            "listed_missing": [],
            "sector_scalar": [],
            "near_duplicate_heading": [],
            "case_variant_heading": [],
            "redundant_yaml": [],
        }
        self.stats = {"total_files": 0, "errors": 0, "warnings": 0}

    # ------------------------------------------------------------------ #
    # logging
    # ------------------------------------------------------------------ #
    def log_issue(self, bucket, file_path, description):
        self.issues.setdefault(bucket, []).append({"file": file_path, "description": description})

    def log_warning(self, bucket, file_path, description):
        self.warnings.setdefault(bucket, []).append({"file": file_path, "description": description})

    # ------------------------------------------------------------------ #
    # filename + name-sync checks
    # ------------------------------------------------------------------ #
    def check_filename_format(self, file_path):
        stem = Path(file_path).stem
        if len(stem) > 100:
            self.log_issue(
                "filename_format",
                file_path,
                f"Filename exceeds 100 chars ({len(stem)})",
            )
            return
        if not _FILENAME_OK.match(stem):
            self.log_issue(
                "filename_format",
                file_path,
                f"Invalid filename (not PascalCase/underscore): {stem}",
            )
            return
        if "__" in stem:
            self.log_issue(
                "filename_format",
                file_path,
                f"Consecutive underscores in filename: {stem}",
            )
            return
        if stem.endswith("_"):
            self.log_issue("filename_format", file_path, f"Trailing underscore in filename: {stem}")

    def check_name_sync(self, file_path, data):
        """normalized_name must be present and equal the filename (minus .md)."""
        nn = data.get("normalized_name")
        stem = Path(file_path).stem
        if not nn:
            self.log_issue("name_sync", file_path, "Missing 'normalized_name' field")
            return
        if nn != stem:
            self.log_issue(
                "name_sync",
                file_path,
                f"normalized_name {nn!r} does not match filename {stem!r}",
            )

    # ------------------------------------------------------------------ #
    # YAML structure + required fields
    # ------------------------------------------------------------------ #
    def check_yaml_structure(self, file_path, content=None):  # noqa: C901
        if content is None:
            try:
                with open(file_path, encoding="utf-8") as f:
                    content = f.read()
            except Exception as e:
                self.log_issue("yaml_structure", file_path, f"Error reading file: {e}")
                return

        lines = content.splitlines()
        separators = [i for i, line in enumerate(lines) if line.strip() == "---"]

        if len(separators) < 2:
            self.log_issue(
                "yaml_structure",
                file_path,
                "Missing proper YAML structure (need --- delimiters)",
            )
            return

        yaml_start, yaml_end = separators[0], separators[1]
        if yaml_end <= yaml_start + 1:
            self.log_issue("yaml_structure", file_path, "Empty YAML block")
            return

        yaml_content = "\n".join(lines[yaml_start + 1 : yaml_end])
        try:
            data = yaml_safe_load(yaml_content)
            if data is None:
                data = {}
        except yaml.YAMLError as e:
            self.log_issue("yaml_structure", file_path, f"Invalid YAML: {e}")
            return

        # Required fields
        missing = [f for f in ("title", "type") if f not in data]
        if missing:
            self.log_issue(
                "yaml_structure",
                file_path,
                f"Missing required fields: {', '.join(missing)}",
            )

        # type value validity
        if "type" in data and data["type"] not in VALID_TYPES:
            self.log_issue(
                "yaml_structure",
                file_path,
                f"Invalid type {data['type']!r} (expected company|sector)",
            )

        # tags list + duplicates
        if "tags" in data:
            if not isinstance(data["tags"], list):
                self.log_issue(
                    "yaml_structure",
                    file_path,
                    "Tags field not properly formatted as list",
                )
            else:
                tags = [str(t).strip() for t in data["tags"]]
                if len(tags) != len(set(tags)):
                    self.log_issue("yaml_structure", file_path, "Duplicate tags found")
                # tag taxonomy format (advisory)
                for t in tags:
                    if not _TAG_OK.match(t):
                        self.log_warning("tag_format", file_path, f"Non-standard tag {t!r}")
                        break
                # tag VALUE drift (advisory): for controlled namespaces, warn on
                # any value outside the known-good set. Unlike tag_format this
                # loops over ALL tags so each unknown value is flagged. Free-
                # vocabulary namespaces are skipped (not in _KNOWN_TAG_VALUES).
                # See doc/improvements/hierarchy_design_roadmap.txt D3.
                for t in tags:
                    ns, sep, val = t.partition("/")
                    if not sep or ns not in _KNOWN_TAG_VALUES:
                        continue
                    if val not in _KNOWN_TAG_VALUES[ns]:
                        self.log_warning(
                            "tag_value",
                            file_path,
                            f"Unknown {ns} value {val!r} (not in the "
                            f"known-good set; add it intentionally or fix the "
                            f"drift)",
                        )

        # name sync (needs parsed data; only meaningful when YAML parsed)
        self.check_name_sync(file_path, data)

        # type-specific consistency
        if data.get("type") == "sector":
            self.check_sector_yaml_consistency(file_path, data, yaml_content)
        elif data.get("type") == "super_sector":
            self.check_super_sector_yaml_consistency(file_path, data, yaml_content)
        elif data.get("type") == "company":
            self.check_company_yaml_consistency(file_path, data, yaml_content)

    def check_sector_yaml_consistency(self, file_path, data, yaml_content):
        # permalink must start with /sectors/
        pl = data.get("permalink")
        if isinstance(pl, str) and not pl.startswith("/sectors/"):
            self.log_issue(
                "yaml_structure",
                file_path,
                f"Permalink must start with '/sectors/': {pl}",
            )

        # dates should be quoted in raw YAML
        for date_field in ("created", "last_modified"):
            if date_field in data and not re.search(rf"{date_field}:\s*'[^']*'", yaml_content):
                self.log_issue(
                    "yaml_structure",
                    file_path,
                    f"{date_field} date should be quoted in YAML",
                )

        # title should NOT be quoted
        if "title" in data:
            m = re.search(r"title:\s*([^'\n]+)", yaml_content)
            if m and m.group(1).strip().startswith('"') and m.group(1).strip().endswith('"'):
                self.log_issue(
                    "yaml_structure",
                    file_path,
                    f"Title should not be quoted in YAML: {m.group(1).strip()}",
                )

        # only expected sector fields
        # NOTE: super_sector is the M4 up-link to the 3-level hierarchy
        # (findata/Super_Sectors); populated by build_sector_hierarchy.py.
        expected = {
            "title",
            "type",
            "super_sector",
            "tags",
            "created",
            "last_modified",
            "normalized_name",
            "permalink",
        } | OKF_OPTIONAL_FIELDS
        unexpected = set(data.keys()) - expected
        if unexpected:
            self.log_issue(
                "yaml_structure",
                file_path,
                f"Unexpected fields in YAML header: {', '.join(unexpected)}",
            )

        # field order: title, type first (stylistic -> advisory)
        if list(data.keys())[:2] != ["title", "type"]:
            self.log_warning(
                "field_order",
                file_path,
                "YAML fields should start with 'title' and 'type'",
            )

    def check_super_sector_yaml_consistency(self, file_path, data, yaml_content):
        """Super-sector-specific checks (findata/Super_Sectors/*.md).

        These notes are GENERATED by build_sector_hierarchy.py (9 GICS-style
        groups), so the field set is tighter and more uniform than hand-
        authored sector/company notes:
          - permalink is `/super_sectors/<slug>` (leading slash, matching the
            /sectors/ and /companies/ convention). The generator emits this
            form; the bare `super_sectors/` form is a legacy artifact that is
            now rejected.
          - NO `super_sector` uplink field (they ARE the top level).
          - `file_path` IS present (the generator writes it; unlike sector/
            company notes where it is absent from YAML).
        """
        # permalink must carry the /super_sectors/ prefix with a LEADING slash.
        pl = data.get("permalink")
        if isinstance(pl, str):
            if not pl.startswith("/super_sectors/"):
                self.log_issue(
                    "yaml_structure",
                    file_path,
                    f"Permalink must start with '/super_sectors/': {pl}",
                )

        # dates should be quoted in raw YAML (shared rule)
        for date_field in ("created", "last_modified"):
            if date_field in data and not re.search(rf"{date_field}:\s*'[^']*'", yaml_content):
                self.log_issue(
                    "yaml_structure",
                    file_path,
                    f"{date_field} date should be quoted in YAML",
                )

        # title should NOT be quoted (shared rule)
        if "title" in data:
            m = re.search(r"title:\s*([^'\n]+)", yaml_content)
            if m and m.group(1).strip().startswith('"') and m.group(1).strip().endswith('"'):
                self.log_issue(
                    "yaml_structure",
                    file_path,
                    f"Title should not be quoted in YAML: {m.group(1).strip()}",
                )

        # only expected super_sector fields. NOTE: file_path IS expected here
        # (the generator writes it), unlike sector/company notes. No
        # `super_sector` uplink field — these ARE the top of the hierarchy.
        expected = {
            "title",
            "type",
            "normalized_name",
            "file_path",
            "permalink",
            "tags",
            "created",
            "last_modified",
        } | OKF_OPTIONAL_FIELDS
        unexpected = set(data.keys()) - expected
        if unexpected:
            self.log_issue(
                "yaml_structure",
                file_path,
                f"Unexpected fields in YAML header: {', '.join(unexpected)}",
            )

        # field order: title, type first (stylistic -> advisory)
        if list(data.keys())[:2] != ["title", "type"]:
            self.log_warning(
                "field_order",
                file_path,
                "YAML fields should start with 'title' and 'type'",
            )

    def check_company_yaml_consistency(self, file_path, data, yaml_content):  # noqa: C901
        """Company-specific checks. Field order is advisory; permalink is gate-failing."""
        pl = data.get("permalink")
        if isinstance(pl, str) and not pl.startswith("/companies/"):
            self.log_issue(
                "yaml_structure",
                file_path,
                f"Permalink must start with '/companies/': {pl}",
            )

        order = list(data.keys())
        if len(order) >= 2 and order[:2] != ["title", "type"]:
            self.log_warning(
                "field_order",
                file_path,
                "YAML fields should start with 'title' and 'type'",
            )

        # recommended fields (advisory)
        for field in ("market_cap",):
            if field not in data:
                self.log_warning(
                    "missing_field",
                    file_path,
                    f"Company missing recommended field '{field}'",
                )

        # market_cap value validity (gate-failing)
        # Canonical set: large_cap | mid_cap | small_cap | micro_cap | null
        # nano_cap merged into micro_cap, mega_cap folded into large_cap (2026-07).
        VALID_CAPS = {"large_cap", "mid_cap", "small_cap", "micro_cap"}
        if "market_cap" in data:
            mc = data["market_cap"]
            if mc is not None and mc not in VALID_CAPS:
                self.log_issue(
                    "market_cap_value",
                    file_path,
                    f"Invalid market_cap {mc!r} (expected one of {sorted(VALID_CAPS)} or null)",
                )

        # title should NOT be quoted (mirrors the sector check; D3 extended this
        # to company notes after a one-time unquote of 421 quoted titles).
        if "title" in data:
            m = re.search(r"title:\s*([^'\n]+)", yaml_content)
            if m and m.group(1).strip().startswith('"') and m.group(1).strip().endswith('"'):
                self.log_warning(
                    "company_title_quoted",
                    file_path,
                    f"Title should not be quoted in YAML: {m.group(1).strip()}",
                )

        # unlisted marker: ticker:null is meaningful (an unlisted company), so
        # it should be explicit rather than implicit-null. Advisory (D3).
        if data.get("ticker") is None and "listed" not in data:
            self.log_warning(
                "listed_missing",
                file_path,
                "ticker is null but no 'listed: false' marker (unlisted is a "
                "meaningful category, mark it explicitly)",
            )

        # sector: scalar should match the canonical PascalCase sector name
        # (case-insensitive). Advisory; the backend derives sector_classification
        # from the sector/* tag, not this scalar, but drift makes notes
        # inconsistent.
        sector_val = data.get("sector")
        if isinstance(sector_val, str) and sector_val.strip():
            v = sector_val.strip()
            if v not in _SECTOR_NAMES:
                if v.lower() in _SECTOR_NAMES_LOWER:
                    self.log_warning(
                        "sector_scalar",
                        file_path,
                        f"sector: {v!r} is non-canonical casing; expected "
                        f"{_SECTOR_LOWER_TO_CANON[v.lower()]!r}",
                    )
                else:
                    self.log_warning(
                        "sector_scalar",
                        file_path,
                        f"sector: {v!r} does not match any canonical sector",
                    )

    # ------------------------------------------------------------------ #
    # content quality
    # ------------------------------------------------------------------ #
    def check_content_quality(self, file_path, content=None):  # noqa: C901
        if content is None:
            try:
                with open(file_path, encoding="utf-8") as f:
                    content = f.read()
            except Exception as e:
                self.log_issue("content_minimal", file_path, f"Error reading file: {e}")
                return

        if len(content) > 1500:
            return

        lines = content.splitlines()
        separators = [i for i, line in enumerate(lines) if line.strip() == "---"]
        if len(separators) < 2:
            return

        yaml_end = separators[1]
        if yaml_end >= len(lines) - 1:
            self.log_issue("content_minimal", file_path, "No content after YAML frontmatter")
            return

        content_after = "\n".join(lines[yaml_end + 1 :])

        meaningful_content = re.sub(r"^\s*$", "", content_after, flags=re.MULTILINE).strip()
        if not meaningful_content:
            self.log_issue("content_minimal", file_path, "No meaningful content after YAML")
            return

        placeholder_patterns = [
            r"More information about this company will be added here",
            r"Information about.*will be added here",
            r"\*Add.*here\.*",
            r"Detail business segments",
            r"Describe competitive positioning",
            r"Include notable quotes if available",
            r"Provide key financial metrics",
        ]

        meaningful_lines = []
        for line in content_after.splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            is_placeholder = any(
                re.search(p, stripped, re.IGNORECASE) for p in placeholder_patterns
            )
            if stripped in ("N/A",) or stripped.lower() == "overview":
                is_placeholder = True
            if not is_placeholder:
                meaningful_lines.append(stripped)

        if len(meaningful_lines) < 2:
            self.log_issue(
                "content_minimal",
                file_path,
                f"Minimal meaningful content ({len(meaningful_lines)} meaningful lines)",
            )

        if not re.search(r"^#", content_after, re.MULTILINE):
            self.log_issue("content_missing_structure", file_path, "Missing main heading")

    # ------------------------------------------------------------------ #
    # content structure: duplicate / near-duplicate headings + redundant YAML
    # ------------------------------------------------------------------ #
    _H3_RE = re.compile(r"^###\s+(.+?)\s*$")
    # Keys that mark a stray embedded frontmatter block when they appear on
    # their own line inside a --- ... --- span in the body.
    _YAML_KEY_RE = re.compile(
        r"^(created|last_modified|normalized_name|market_cap|permalink|ticker|"
        r"title|type|sector|super_sector|file_path):"
    )
    # Known false-positive suffix pattern: two headings sharing the same
    # category word but describing different sub-types (e.g. "two wheelers"
    # alongside "commercial vehicles"). Mirrors dedupe_section_headings.py.
    _EXCLUDE_SUFFIXES = (
        " apparel",
        " technology",
        " pay later",
        " wheelers",
        " wear",
        " scooters",
        " bikes",
    )

    @staticmethod
    def _norm_heading(h: str) -> str:
        return re.sub(r"[^a-z0-9]+", " ", h.lower()).strip()

    def _heading_false_positive(self, h1, h2):
        """Mirror dedupe_section_headings._should_exclude."""
        a = self._norm_heading(h1)
        b = self._norm_heading(h2)
        for suffix in self._EXCLUDE_SUFFIXES:
            if a.endswith(suffix) and b.endswith(suffix):
                return True
        if a.startswith("on ") and b.startswith(a[3:]):
            return True
        if b.startswith("on ") and a.startswith(b[3:]):
            return True
        return False

    def check_heading_duplicates(self, file_path, content=None):  # noqa: C901
        """Duplicate / near-duplicate / case-variant H3 headings + stray YAML.

        Mirrors helpers/maintenance/dedupe_section_headings.py so the issues it
        reports (exact-dup, near-dup, case-variant, redundant-YAML headings)
        surface under the normal `verify_notes.py` run instead of a separate
        maintenance pass.
        """
        if content is None:
            try:
                content = open(file_path, encoding="utf-8").read()
            except Exception:
                return
        lines = content.splitlines()

        heads: list[tuple[int, str]] = []
        for i, line in enumerate(lines, start=1):
            m = self._H3_RE.match(line)
            if m:
                heads.append((i, m.group(1).strip()))
        if not heads:
            return

        # 1. exact + case-variant heading text
        counts = Counter(h for _, h in heads)
        for h, c in counts.items():
            if c > 1:
                self.log_issue(
                    "duplicates",
                    file_path,
                    f"Duplicate {h!r} heading appears {c}x "
                    f"(lines {[ln for ln, hh in heads if hh == h]})",
                )

        # 2. case variants (advisory)
        for h in counts:
            variants = sorted({hh for _, hh in heads if hh.lower() == h.lower()})
            if len(variants) > 1:
                self.log_warning(
                    "case_variant_heading",
                    file_path,
                    f"Casing variants of {h.lower()!r}: {variants}",
                )

        # 3. near duplicates (>= 0.90 similarity, ignoring known false positives)
        # Pre-normalize once (the O(n²) loop re-reads each heading many times).
        # The naive all-pairs SequenceMatcher was the verify_notes hot path
        # (~5s on 1101 files); the length + shared-character guards below skip
        # the expensive difflib call for pairs that cannot reach 0.90.
        normed = [(ln, h, self._norm_heading(h)) for ln, h in heads]
        for i in range(len(normed)):
            ln1, h1, a = normed[i]
            if not a:
                continue
            for j in range(i + 1, len(normed)):
                ln2, h2, b = normed[j]
                if not b or h1.lower() == h2.lower():
                    continue
                # Cheap guard: ratio() = 2*matches/(la+lb) <= 2*min(la,lb)/(la+lb),
                # so if 2*min/(la+lb) < 0.80 the pair can't reach 0.90. The 0.80
                # floor (below the 0.90 target) leaves headroom so suffix-difference
                # near-dupes like "Strategic Initiatives" vs "...Plan" (real sim
                # ~0.94 but length-bound ~0.89) still reach difflib.
                la, lb = len(a), len(b)
                if 2 * min(la, lb) < 0.80 * (la + lb):
                    continue
                if self._heading_false_positive(h1, h2):
                    continue
                sm = SequenceMatcher(None, a, b)
                # quick_ratio() is a cheap upper bound on ratio(); if it can't
                # reach the 0.90 threshold the expensive full ratio() is skipped.
                if sm.quick_ratio() < 0.90:
                    continue
                sim = sm.ratio()
                if sim >= 0.90:
                    self.log_warning(
                        "near_duplicate_heading",
                        file_path,
                        f"Near-duplicate headings: line {ln1} {h1!r} <-> "
                        f"line {ln2} {h2!r} (similarity {sim:.3f})",
                    )

        # 4. redundant embedded YAML in the body (after the real frontmatter)
        seps = [i for i, line in enumerate(lines) if line.strip() == "---"]
        if len(seps) < 2 or seps[0] != 0:
            return
        body_start = seps[1]
        for a, b in zip(seps, seps[1:]):
            if a <= body_start:
                continue
            seg = lines[a + 1 : b]
            keys = []
            for line in seg:
                s = line.strip()
                m = self._YAML_KEY_RE.match(s)
                if m:
                    keys.append(s.split(":")[0])
                elif s.startswith("*Last Updated"):
                    keys.append("last-updated")
            key_only = [k for k in keys if k != "last-updated"]
            if key_only and key_only[0] in (
                "created",
                "last_modified",
                "normalized_name",
                "market_cap",
                "permalink",
                "ticker",
                "title",
                "type",
                "sector",
                "super_sector",
            ):
                self.log_warning(
                    "redundant_yaml",
                    file_path,
                    f"Redundant embedded YAML block rows {a + 1}-{b} "
                    f"[{', '.join(dict.fromkeys(keys))}]",
                )

    # ------------------------------------------------------------------ #
    # driver
    # ------------------------------------------------------------------ #
    def process_directory(self, dir_path, dir_type):
        path = Path(dir_path)
        if not path.exists() or not path.is_dir():
            if not self.suppress_progress:
                print(f"❌ Directory not found: {dir_path}")
            return

        if not self.suppress_progress:
            print(f"🔍 Checking {dir_type} directory: {dir_path}")
        file_count = 0
        for md_file in path.rglob("*.md"):
            if not md_file.is_file():
                continue
            file_count += 1
            self.stats["total_files"] += 1
            # Read once, pass the content string to the three checks that
            # need it (each previously opened+read the file independently —
            # 3× I/O on the 1102-note corpus).
            try:
                content = md_file.read_text(encoding="utf-8")
            except Exception as e:
                self.log_issue("yaml_structure", str(md_file), f"Error reading file: {e}")
                content = None
            self.check_filename_format(str(md_file))
            self.check_yaml_structure(str(md_file), content=content)
            self.check_content_quality(str(md_file), content=content)
            self.check_heading_duplicates(str(md_file), content=content)
        if not self.suppress_progress:
            print(f"   Checked {file_count} files in {dir_type}")
        return file_count

    def _totals(self):
        errors = sum(len(v) for v in self.issues.values())
        warnings = sum(len(v) for v in self.warnings.values())
        self.stats["errors"] = errors
        self.stats["warnings"] = warnings
        return errors, warnings

    def generate_report(self, output_file="verify_notes_report.txt"):
        errors, warnings = self._totals()

        with open(output_file, "w", encoding="utf-8") as f:
            f.write("FinData Knowledge Graph - Notes Verification Report\n")
            f.write("=" * 60 + "\n")
            f.write(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"Project Root: {self.project_root}\n")
            f.write(f"Total Files Checked: {self.stats['total_files']}\n")
            f.write(f"ERRORS: {errors}   WARNINGS: {warnings}\n\n")

            f.write("## ERRORS (gate-failing)\n\n")
            for bucket, items in self.issues.items():
                if items:
                    f.write(f"### {bucket} ({len(items)})\n")
                    for issue in items:
                        f.write(f"- {issue['file']}: {issue['description']}\n")
                    f.write("\n")

            if any(self.warnings.values()):
                f.write("## WARNINGS (advisory)\n\n")
                for bucket, items in self.warnings.items():
                    if items:
                        f.write(f"### {bucket} ({len(items)})\n")
                        for w in items:
                            f.write(f"- {w['file']}: {w['description']}\n")
                        f.write("\n")

            f.write("## Summary\n" + "=" * 20 + "\n")
            f.write(f"Total files checked: {self.stats['total_files']}\n")
            f.write(f"Errors: {errors}\nWarnings: {warnings}\n\n")
            if errors == 0:
                f.write("✅ All notes passed verification (no errors).\n")
            else:
                f.write(f"⚠️  Found {errors} errors that need attention.\n")

        return errors

    def verify_all(self):
        print("🚀 Starting comprehensive notes verification...")
        print("=" * 60)

        output_file = str(self.project_root / "verify_notes_report.txt")

        dirs, labels, sectors_count, super_sectors_count = _collect_scan_dirs(self.project_root)

        # Count total files to decide serial vs parallel. The threshold avoids
        # ProcessPool startup overhead (~0.3s) on small inputs / test fixtures.
        total_files = sum(sum(1 for _ in Path(d).rglob("*.md") if _.is_file()) for d in dirs)
        use_parallel = total_files >= _PARALLEL_THRESHOLD

        if use_parallel:
            workers = min(4, os.cpu_count() or 1)
            print(f"   Parallel mode: {len(dirs)} dirs across {workers} workers")
            companies_count = 0
            with ProcessPoolExecutor(max_workers=workers) as ex:
                for issues, warnings, count in ex.map(_process_dir_worker, dirs):
                    for bucket, items in issues.items():
                        self.issues.setdefault(bucket, []).extend(items)
                    for bucket, items in warnings.items():
                        self.warnings.setdefault(bucket, []).extend(items)
                    self.stats["total_files"] += count or 0
            # Sectors/Super_Sectors are already counted by _collect_scan_dirs;
            # companies = total minus those two.
            companies_count = self.stats["total_files"] - (sectors_count + super_sectors_count)
        else:
            # Serial path (small inputs / tests).
            sectors_count = (
                self.process_directory(self.project_root / "findata" / "Sectors", "Sectors") or 0
            )
            super_sectors_count = (
                self.process_directory(
                    self.project_root / "findata" / "Super_Sectors", "Super_Sectors"
                )
                or 0
            )
            companies_count = (
                self.process_directory(self.project_root / "findata" / "Companies", "Companies")
                or 0
            )

        errors, warnings = self._totals()

        print("\n" + "=" * 60)
        print("📊 Verification Summary:")
        print(f"   Sectors checked: {sectors_count}")
        print(f"   Super-sectors checked: {super_sectors_count}")
        print(f"   Companies checked: {companies_count}")
        print(f"   Total files: {self.stats['total_files']}")
        print(f"   Errors: {errors}   Warnings: {warnings}")

        self.generate_report(output_file)

        if errors == 0:
            print("✅ All notes passed verification! (warnings advisory)")
        else:
            print(f"⚠️  Found {errors} errors. See {output_file} for details.")
        return errors


# ------------------------------------------------------------------ #
# Directory-sharded parallelism
# ------------------------------------------------------------------ #
# The corpus is 1102 notes across 45 scan directories (Sectors, Super_Sectors,
# and 43 Companies/<sector> dirs). Each directory is independent — its files
# are checked in isolation with no cross-directory state. Sharding by
# directory lets a ProcessPoolExecutor fan out across cores with minimal IPC
# (each worker returns only the issues/warnings dicts it found, not per-file
# data). The CPU-bound checks (YAML parse, difflib near-dup) are GIL-bound, so
# threads don't help — processes are required.
#
# Below a file-count threshold the serial path is used (ProcessPool startup
# overhead ~0.3s exceeds the speedup on small inputs).

# Minimum total file count to justify spawning worker processes.
_PARALLEL_THRESHOLD = 100


def _collect_scan_dirs(project_root):
    """Build the list of leaf scan directories under findata/.

    Returns (dirs, labels, sector_count, super_sector_count) where dirs is the
    flat list of directories to check and labels are their display names.
    Sectors and Super_Sectors are scanned as single dirs; Companies is sharded
    by its 43 sector subdirectories so each sector dir is an independent shard.
    """
    findata = Path(project_root) / "findata"
    dirs: list[str] = []
    labels: list[str] = []
    s_count = ss_count = 0

    sectors = findata / "Sectors"
    if sectors.is_dir():
        dirs.append(str(sectors))
        labels.append("Sectors")
        s_count = sum(1 for _ in sectors.rglob("*.md") if _.is_file())

    super_sectors = findata / "Super_Sectors"
    if super_sectors.is_dir():
        dirs.append(str(super_sectors))
        labels.append("Super_Sectors")
        ss_count = sum(1 for _ in super_sectors.rglob("*.md") if _.is_file())

    companies = findata / "Companies"
    if companies.is_dir():
        for sector_dir in sorted(companies.iterdir()):
            if sector_dir.is_dir():
                dirs.append(str(sector_dir))
                labels.append(sector_dir.name)

    return dirs, labels, s_count, ss_count


def _process_dir_worker(dir_path):
    """Process one scan directory in a worker process.

    Creates a fresh NotesVerifier, runs all checks on the directory, and
    returns the issues/warnings dicts + file count. Must be module-level
    (not a method) so it's picklable by ProcessPoolExecutor.
    """
    v = NotesVerifier()
    v.suppress_progress = True  # workers print nothing (avoids interleaving)
    count = v.process_directory(dir_path, Path(dir_path).name)
    return v.issues, v.warnings, count


def main():
    return NotesVerifier().verify_all()


if __name__ == "__main__":
    sys.exit(main())
