-- LIVE DDL dump — generated by helpers/misc/schema_dump.py; DO NOT EDIT
-- source: memory/convo_search.duckdb (duckdb)
-- body sha256: bf3c5ca3e395
-- refresh: make schema-dump
CREATE TABLE convo_meta("key" VARCHAR PRIMARY KEY, "value" VARCHAR);
CREATE TABLE convo_search(harness VARCHAR, session_id VARCHAR, part_id VARCHAR, file_path VARCHAR, row_no BIGINT, ts TIMESTAMP, "role" VARCHAR, agent VARCHAR, model VARCHAR, part_type VARCHAR, text_len BIGINT, snippet VARCHAR, embedding FLOAT[], PRIMARY KEY(harness, part_id));
CREATE TABLE harvest_meta("source" VARCHAR PRIMARY KEY, watermark VARCHAR, updated_ts TIMESTAMP);
CREATE TABLE part_index(harness VARCHAR, part_id VARCHAR, session_id VARCHAR, PRIMARY KEY(harness, part_id));
