-- LIVE DDL dump — generated by helpers/misc/schema_dump.py; DO NOT EDIT
-- source: memory/data/model_usage.duckdb (duckdb)
-- body sha256: 305cef2df22e
-- refresh: make schema-dump
CREATE TABLE fact_usage("source" VARCHAR, "day" DATE, provider VARCHAR, model VARCHAR, reqs BIGINT NOT NULL, fresh_in BIGINT NOT NULL, cached BIGINT NOT NULL, cache_write BIGINT NOT NULL, output BIGINT NOT NULL, reasoning BIGINT NOT NULL, tokens BIGINT NOT NULL, cost_usd DOUBLE NOT NULL, cost_basis VARCHAR NOT NULL, loaded_at TIMESTAMP NOT NULL, PRIMARY KEY("source", "day", provider, model));
CREATE TABLE load_log("source" VARCHAR NOT NULL, started_at TIMESTAMP NOT NULL, "rows" BIGINT NOT NULL, status VARCHAR NOT NULL, detail VARCHAR);
